version: '3'
services:
  unhealthy-autostart:
    image: ghcr.io/mrdrache333/docker-unhealthy-autorestart
    environment:
      - BOT_API_KEY=BOT_API_TOKEN
      - CHAT_ID=YOUR_CHAT_ID
      - HOST_ALIAS=MyHost
      # Optional: Blacklisted containers that will not be restarted
      - BLACKLIST="container1 container2"
      # Optional: Blacklisted containers that will be restarted, but without notification
      - NOTIFY_BLACKLIST="container1 container2"
      # Optional: Send Notification when container started (Default=false)
      - START_MESSAGE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
