version: '3'
services:
  unhealthy-autostart:
    image: mrdrache333/unhealthy-autostart
    environment:
      - BOT_API_KEY=BOT_API_TOKEN
      - CHAT_ID=YOUR_CHAT_ID
      - HOST_ALIAS=MyHost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
