version: '3'
services:
  unhealthy-autostart:
    image: docker-unhealthy-autorestart
    environment:
      # Poll interval (in seconds). This value controls how frequently the Container will check for unhealty containers. 
      - POLL_INTERVAL=60
      # Optional: Blacklisted containers that will not be restarted
      - BLACKLIST=""
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /etc/localtime:/etc/localtime:ro
